networks: {}
services:
  elasticsearch:
    image: elasticsearch:5.6.4
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data:rw
  kibana:
    depends_on:
    - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    image: kibana:5.6.4
    ports:
    - 5601:5601
version: '2.0'
volumes:
  elasticsearch: {}
